//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApplication1.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ConsoleApplication1.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html&gt;
        ///&lt;head&gt;
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///    &lt;div style=&quot; position:fixed; top:50%; left:50%; margin-top:-150px; margin-left:-200px;&quot;&gt;
        ///        &lt;img src=&quot;https://media.giphy.com/media/gaS3J1JB4NCaA/giphy.gif&quot; style=&quot;width:400px; height:300px;&quot;&gt;
        ///        &lt;a href=&quot;http://localhost/c/page2&quot;&gt;Next&lt;/a&gt;
        ///    &lt;/div&gt;
        ///
        ///&lt;audio autoplay&gt;
        ///  &lt;source preload=&quot;auto&quot; src=&quot;https://drive.google.com/a/avans.nl/file/d/0B5Oar9gVI9Xbbk9lTzZHbU5LYUk/preview&quot; type=&quot;audio/ogg&quot;&gt;
        ///&lt;/audio&gt;
        ///&lt;/body&gt;
        ///&lt;/html&gt;.
        /// </summary>
        internal static string page1 {
            get {
                return ResourceManager.GetString("page1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html&gt;
        ///&lt;head&gt;
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///    &lt;div style=&quot; position:fixed; top:50%; left:50%; margin-top:-150px; margin-left:-200px;&quot;&gt;
        ///        &lt;img src=&quot;http://loredebacker.donboscohalle.net/websites/Tekenfilm/beeld/beeld4.jpg&quot; style=&quot;width:400px; height:300px;&quot;&gt;
        ///        &lt;a href=&quot;http://localhost/c/page3&quot;&gt;Next&lt;/a&gt;
        ///    &lt;/div&gt;
        ///
        ///&lt;/body&gt;
        ///&lt;/html&gt;.
        /// </summary>
        internal static string page2 {
            get {
                return ResourceManager.GetString("page2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html&gt;
        ///&lt;head&gt;
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///    &lt;div style=&quot; position:fixed; top:50%; left:50%; margin-top:-150px; margin-left:-200px;&quot;&gt;
        ///        &lt;img src=&quot;https://media.giphy.com/media/gaS3J1JB4NCaA/giphy.gif&quot; style=&quot;width:400px; height:300px;&quot;&gt;
        ///        &lt;a href=&quot;http://localhost/c/page4&quot;&gt;Next&lt;/a&gt;
        ///    &lt;/div&gt;
        ///
        ///&lt;audio autoplay&gt;
        ///  &lt;source preload=&quot;auto&quot; src=&quot;https://drive.google.com/a/avans.nl/file/d/0B5Oar9gVI9Xbbk9lTzZHbU5LYUk/preview&quot; type=&quot;audio/ogg&quot;&gt;
        ///&lt;/audio&gt;
        ///&lt;/body&gt;
        ///&lt;/html&gt;.
        /// </summary>
        internal static string page3 {
            get {
                return ResourceManager.GetString("page3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html&gt;
        ///&lt;head&gt;
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///&lt;audio autoplay&gt;
        ///  &lt;source src=&quot;http://s3.argim.net/files/r/spongebob_the_big_laugh.mp3&quot; type=&quot;audio/mp3&quot;&gt;
        ///&lt;/audio&gt;
        ///    &lt;div style=&quot; position:fixed; top:50%; left:50%; margin-top:-150px; margin-left:-200px;&quot;&gt;
        ///        &lt;img src=&quot;https://media0.giphy.com/media/cYVpEseXlkS1q/200.gif&quot; style=&quot;width:400px; height:300px;&quot;&gt;
        ///		&lt;a href=&quot;http://localhost/c/page1&quot;&gt;reset&lt;/a&gt;
        ///    &lt;/div&gt;
        ///&lt;/body&gt;
        ///&lt;/html&gt;.
        /// </summary>
        internal static string page4 {
            get {
                return ResourceManager.GetString("page4", resourceCulture);
            }
        }
    }
}
